APP_NAME = "RangeLens"
APP_VERSION = "0.1.0"
DEFAULT_DB_PATH = "rangelens.db"

OPTISHOT_VENDOR_ID = 0x0547
OPTISHOT_PRODUCT_ID = 0x3294
OPTISHOT_REPORT_SIZE = 60
OPTISHOT_SUBPACKET_SIZE = 5

OPTISHOT_SIGNATURE_ORIGIN = 0x81
OPTISHOT_SIGNATURE_FRONT = 0x4A
OPTISHOT_SIGNATURE_CONTINUED = 0x52

OPTISHOT_CMD_ENABLE_SENSORS = 0x50
OPTISHOT_CMD_LED_RED = 0x51
OPTISHOT_CMD_LED_GREEN = 0x52
OPTISHOT_CMD_SHUTDOWN = 0x80

OPTISHOT_SENSOR_SPACING = 185
OPTISHOT_LED_SPACING = 15
OPTISHOT_SPEED_CONVERSION_FACTOR = 2236.94
OPTISHOT_CAPTURE_TIMEOUT_SECONDS = 5.0
OPTISHOT_READ_TIMEOUT_MS = 50
